#kakao.authorization-grant-type=authorization_code
#kakao.redirect-uri= ${KAKAO_REDIRECT_URI}
#kakao.client-id=${KAKAO_CLIENT_ID}
#kakao.client-secret=${KAKAO_CLIENT_SECRET}
#
#provider.kakao.authorization-uri=${KAKAO_AUTHORIZATION_URI}?response_type=code&client_id=${KAKAO_CLIENT_ID}&redirect_uri=${KAKAO_REDIRECT_URI}
#provider.kakao.token-uri=${KAKAO_TOKEN_URI}
#provider.kakao.user-info-uri=${KAKAO_USER_INFO_URI}
#
#
#jwt.secret-key=${JWT_SECRET_KEY}
#


spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: ${BASE_URL}/api/login/oauth2/code/kakao
            client-name: Kakao


        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-info-authentication-method: header
            user-name-attribute: id # Kakao ?? ? id, connected_at, properties, kakao_account ? id ??

    jwt:
      secret-key: ${JWT_SECRET_KEY}