spring:
  security:
    basic:
      enabled: true
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: ${BASE_URL}/login/oauth2/code/kakao
            client-name: Kakao

          line:
            client-id: ${LINE_CLIENT_ID}
            client-secret: ${LINE_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: ${BASE_URL}/login/oauth2/code/line
            client-name: line
            scope: profile, openid


        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-info-authentication-method: header
            user-name-attribute: id # Kakao ?? ? id, connected_at, properties, kakao_account ? id ??

          line:
            authorization-uri: https://access.line.me/oauth2/v2.1/authorize
            token-uri: https://api.line.me/oauth2/v2.1/token
            user-info-uri: https://api.line.me/oauth2/v2.1/userinfo
            user-info-authentication-method: header
            user-name-attribute: sub
            jwk-set-uri: https://api.line.me/oauth2/v2.1/certs

    jwt:
      secret-key: ${JWT_SECRET_KEY}