server:
  servlet:
    context-path: /api
    port: 8080

# DB와 secret key 세팅 값
spring:
  profiles:
    active: prod
    include: secret
  data:
    redis:
      lettuce:
        cluster:
          refresh:
            adaptive: true
      host: ${REDIS_HOST}
      port: ${REDIS_PROD_PORT}
---
spring:
  profiles:
    active: dev
    include: secret
  data:
    redis:
      lettuce:
        cluster:
          refresh:
            adaptive: true
      host: ${REDIS_HOST}
      port: ${REDIS_DEV_PORT}
---
spring:
  profiles:
    active: local
    include: secret
  data:
    redis:
      lettuce:
        cluster:
          refresh:
            adaptive: true
      host: ${REDIS_HOST}
      port: ${REDIS_LOCAL_PORT}

  jpa:
    hibernate:
      format_sql: true
      show_sql: false

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 25MB

cloud:
  aws:
    s3:
      bucket: ${BUCKET_NAME}
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: ${ACCESS_KEY}
      secretKey: ${SECRET_KEY}


